paths:
  /api/products:
    get:
      summary: 'Retorna todos los productos disponibles'
      tags:
        - Products MongoDB
      responses:
        "200":
          description: 'OK'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        "500":
          description: 'ERROR general'

  /api/products/{pid}:
    get:
      summary: 'Retorna un producto por id'
      tags: 
        - Products MongoDB
      parameters:
        - name: pid
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "500":
          description: 'ERROR general'

    put:
      summary: 'Actualiza un producto por ID'
      tags:
        - Products MongoDB
      parameters:
        - in: path
          name: pid
          required: true
          description: ID del producto a actualizar
          schema:
            type: string
        - in: body
          name: body
          description: Datos del producto a actualizar
          required: true
          schema:
            $ref: '#/components/schemas/Product'
      responses:
        "200":
          description: 'Producto actualizado exitosamente'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "404":
          description: 'Producto no encontrado'
        "500":
          description: 'Error interno del servidor'
    delete:
      summary: Elimina un producto por su ID
      tags:
        - Products MongoDB
      parameters:
        - name: pid
          in: path
          description: ID del producto a eliminar
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Producto eliminado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  Deleted_product:
                    type: object
                    properties:
                      _id:
                        type: string
                        description: ID del producto eliminado
                      title:
                        type: string
                        description: Nombre del producto eliminado
                      description:
                        type: string
                        description: Descripción del producto eliminado
        "404":
          description: El producto no fue encontrado
        "403":
          description: Acceso denegado. No eres el propietario de este producto o no tienes permisos de administrador
        "500":
          description: Error interno del servidor al intentar eliminar el producto

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: objectId
          description: 'ID del producto en MongoDB'
        title:
          type: string
          description: 'Nombre del producto'
        description:
          type: string
          description: 'Descripcion del producto '
        code:
          type: string
          description: 'Codigo del producto'
        price:
          type: number
          description: 'Precio del producto'
        stock:
          type: number
          description: 'Stock del producto'
        category:
          type: string
          description: 'Categoria del producto'
        thumbnail:
          type: string
          description: 'Imagen del producto'
        status:
          type: string
          description: 'estado del producto'
        owner:
          type: string
          description: 'correo del creador'

      example:
        _id: 65da72fe8e5f14020337ed5a
        title: 'pap'
        description: 'papa'
        code: 'papa'
        price: 234
        stock: 43
        category: 'papa'
        thumbnail: 'Sin imagen'
        status: true
        owner: 'adminCoder@coder.com'

  requestBodies:
    updateProduct:
      content:
        application/json:
          schema:
            type: object
            properties:
              title:
                type: string
              description:
                type: string
              code:
                type: string
              price:
                type: number
              stock:
                type: number
              category:
                type: string
              thumbnail:
                type: string
              status:
                type: string
              owner:
                type: string
